#!/bin/bash

version=`git log --date=iso --pretty=format:"%cd @%H" -1`
if [ $? -ne 0 ]; then
    version="unknown version"
fi

compile=`date +"%F %T %z"`" by "`go version`
if [ $? -ne 0 ]; then
    compile="unknown datetime"
fi

describe=`git describe --tags 2>/dev/null`
if [ $? -eq 0 ]; then
    version="${version} @${describe}"
fi

mkdir -p bin

cat << EOF > bin/version
version = $version
compile = $compile
EOF

utils_pkg="github.com/CodisLabs/codis/pkg/utils"

escape_ldflags_value() {
    printf "%s" "$1" | sed "s/'/'\\\\''/g"
}

version_ldflags=$(escape_ldflags_value "$version")
compile_ldflags=$(escape_ldflags_value "$compile")

cat << EOF > bin/version.ldflags
-X '${utils_pkg}.Version=${version_ldflags}' -X '${utils_pkg}.Compile=${compile_ldflags}'
EOF
